// taskslice.ts
import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { Task } from '../../components/molecules/taskform'; // Import Task interface

// Define the initial state for tasks
interface TaskState {
  tasks: Task[];
}

const initialState: TaskState = {
  tasks: [],
};

// Create a slice for managing tasks
const taskSlice = createSlice({
  name: 'tasks',
  initialState,
  reducers: {
    // Add a reducer for adding a new task
    addTask(state, action: PayloadAction<Task>) {
      state.tasks.push(action.payload);
    },
    // Add other reducers as needed (e.g., for updating or deleting tasks)
  },
});

// Export action creators generated by createSlice
export const { addTask } = taskSlice.actions;

// Export the reducer function generated by createSlice
export default taskSlice.reducer;
